### ISSUE TITLE
Observaciones Generales

### ISSUE THREAD

**Issue by cesaramirez** [irenehl/LaravelAPI#1]
1. El nombramiento a los modelos esta incorrecto, las buenas practicas solo nos indican que debe de ser nada mas el nombre la entidad, en lugar de `ProductModel`, solamente `Product`, 

- [Link de referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Models/ProductModel.php#L8)
- [Naming Convention](https://github.com/alexeymezenin/laravel-best-practices#follow-laravel-naming-conventions)

2. Con respecto al redireccionamiento del reset password, ha quedado hardcode la url base, ¿qué pasara si lo desplegamos en un servidor en producción? siempre estará redirigiéndo a localhost

- [Link de referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Models/User.php#L52)
- [Documentación Laravel](https://laravel.com/docs/8.x/passwords)

3. ¿Por que crear una `function paginate`? por defecto Laravel ya maneja ese metodo en sus modelos
- [Link de referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Http/Controllers/ProductController.php#L22)
- [Buena practica](https://laravel.com/docs/8.x/eloquent-resources#pagination)

4. Para validar un request y posterior crear el modelo hay diferente formas, como esta implementado actualmente es una manera, pero no es la mejor, comparto cual es la mejor manera.
- [Link de referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Http/Controllers/ProductController.php#L41)
- [Buena practica](https://github.com/alexeymezenin/laravel-best-practices#validation)

5. Es una mala practica no utilizar llaves en las condicionales en PHP, esto no es javascript
- [Referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Http/Controllers/ProductController.php#L48)

6. Al retornar un modelo, ya sea index, store, show, este debe de devolver con un enfoque de json en un API y no de la manera como esta actualmente, para eso se ocupa la caracteristica llamada API Resource
- [Referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Http/Controllers/ProductController.php#L51)
- [Buena practica](https://laravel.com/docs/8.x/eloquent-resources#introduction)

7. Aqui hay una falla bastante grande ya que no se estan usando las bondades de Laravel y es usar el Route Model Binding
- [Referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Http/Controllers/ProductController.php#L60)
- [Buena practica](https://laravel.com/docs/8.x/routing#route-model-binding)

8. Este tipo de logica se puede reutilizar e incluso utilizar la acción de index para realizar un buscar, y facilmente se puede agregar scopes en el model para distribuir la logica entre modelo y controlador
- [Referencia](https://github.com/irenehl/LaravelAPI/blob/a73d7042e2fad7e7c1377b316204060118830a3b/app/Http/Controllers/ProductController.php#L97)
- [Buena practica](https://github.com/alexeymezenin/laravel-best-practices#fat-models-skinny-controllers)

9. Laravel ya dispone de ciertos paquetes para optimizar comportamiento de reset password, paquetes como ellos son Breeze, Jetstream entre otros favor revisar

Todas las observaciones deben de ser corregidas y ser reflejadas en los diferentes controladores o entidades que apliquen, te dejo los siguientes links de buenas practicas y recomendacines, favor revisarlas y utilizarlas de ahora en adelante:

- [Laravel best practices](https://github.com/alexeymezenin/laravel-best-practices)
- Recomiendo dar un recorrido por la documentación de Laravel para que veas de todo lo que es capaz de realizar y toda la ayuda que nos puede brindar al realizar un proyecto: https://laravel.com
- Ademas leer sobre los PHP standards [PSR-1](https://www.php-fig.org/psr/psr-1/), [PSR-12](https://www.php-fig.org/psr/psr-12/)

**Comment by irenehl** [comment]
## Tomando en cuenta las recomendaciones dadas, se han hecho los siguientes cambios:

Se hizo el cambio de ProductModels a Product para seguir la convención dada. Se puede revisar en:  [nombre modelos](https://github.com/irenehl/LaravelAPI/tree/master/app/Models)

En esta sección, se creo un archivo llamado values.php que se encarga de leer el contenido de APP_HOST que es un dato en .env (este dato tiene que encontrarse también en el sitio en el que se haga deploy) con esto, ya se tiene que primero agarre la ruta colocada en el APP_HOST y si en dado caso eso no existiera, tomará `localhost` por defecto. Se puede revisar este cambio en:  [Cambio hardcode](https://github.com/irenehl/LaravelAPI/blob/master/config/values.php)

En base a la documentación, se hizo el cambio y se removió la función de `paginate` que esta por gusto ya que Laravel nos provee por defecto de una paginación. Se puede ver el cambio aquí:  [Cambio paginación](https://github.com/irenehl/LaravelAPI/blob/b588abc0a310712f9c2f4fd5a8d08a5d7cfef5b8/app/Http/Controllers/UserController.php#L23)

Se realizaron los siguientes request `LoginRequest`, `ProductStoreRequest` y `UserStoreRequest` siguiendo las indicaciones dadas en la documentación. La implementación se puede ver aquí: [Requests](https://github.com/irenehl/LaravelAPI/tree/master/app/Http/Requests)

Se implementaron los recursos para ver los datos de manera individual y en paginación. Implementación acá: [Enfoque JSON](https://github.com/irenehl/LaravelAPI/tree/master/app/Http/Resources)

Se implementó Route Binding para realizar las búsquedas a partir del modelo. Se puede revisar aquí:  [Route Binding](https://github.com/irenehl/LaravelAPI/blob/master/routes/api.php)
